export const mockBuilds = [
  {
    _class: "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    building: false,
    description: null,
    displayName: "#1532 - In progress",
    id: "1532",
    number: 1532,
    result: null,
    url: "https://jenkins.mydomain.dev/job/Project/job/a-repository/job/main/1532/",
    inProgress: true,
  },
  {
    _class: "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    building: false,
    description: null,
    displayName: "#1531 - Built version 2.0.0",
    id: "1531",
    number: 1531,
    result: "SUCCESS",
    url: "https://jenkins.mydomain.dev/job/Project/job/a-repository/job/main/1531/",
    inProgress: false,
  },
  {
    _class: "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    building: false,
    description: null,
    displayName: "#1530 - Aborted build with longer desctiption",
    id: "1530",
    number: 1530,
    result: "ABORTED",
    url: "https://jenkins.mydomain.dev/job/Project/job/a-repository/job/main/1530/",
    inProgress: false,
  },
  {
    _class: "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    building: false,
    description: null,
    displayName: "#1529 - Aborted build",
    id: "1529",
    number: 1529,
    result: "ABORTED",
    url: "https://jenkins.mydomain.dev/job/Project/job/a-repository/job/main/1529/",
    inProgress: false,
  },
  {
    _class: "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    building: false,
    description: null,
    displayName: "#1528- Built version 1.0.0",
    id: "1528",
    number: 1528,
    result: "SUCCESS",
    url: "https://jenkins.mydomain.dev/job/Project/job/a-repository/job/main/1528/",
    inProgress: false,
  },
];
